export default {
    "home.text.title.part1": "Привет!",
    "home.text.title.part2": "Я Станислав",
    "home.text.title.part3": "Frontend developer",
    "home.text.button.resume": "Резюме",
    "home.text.button.contact": "Связаться со мной",
    "sidebar.name": "Станислав",
    "sidebar.menu.link1": "Опыт",
    "sidebar.menu.link2": "Навыки",
    "sidebar.menu.link3": "Код",
    "sidebar.menu.link4": "Связаться",
    "experience.text.title": "Опыт",
    "experience.text.p1": "В данный момент являюсь разработчиком на ReactJS с почти 3-х летним опытом с данной технологией и более чем 5-ти летним стажем работы в ИТ суммарно.",
    "experience.text.p2": "Неполный перечень моих обязанностей: разработка с нуля, поддерживание легаси проектов, редизайн готового продукта без затрагивания функционала, оптимизация загрузки страницы, улучшение позиционирования сайтов в поисковых системах, внедрение shecma.org разметки, работа с графикой (svg, анимации, различные медиа), верстка, внедрение системы git, интеграция различных сторонних сервисов, работа с СMS...",
    "experience.placeofwork1.position": "Frontend developer",
    "experience.placeofwork1.company": "Skillsetter",
    "experience.placeofwork1.dates": "07.2021 — 01.2023",
    "experience.placeofwork1.description": "Разработка образовательной платформы включающей в себя лендинги, учебные курсы, задачи с обработкой ответов и прочее.\nПеренос существующего функционала с twig на react, разработка нового функционала на react, верстка как на html/sass так и с помощью styled-components, редизайн.\nВ качестве стейт-менеджера использовался React Context. Небольшое количество ванильного JS.",
    "experience.placeofwork2.position": "Frontend developer",
    "experience.placeofwork2.company": "Easy Agency",
    "experience.placeofwork2.dates": "09.2019 — 04.2021",
    "experience.placeofwork2.description": "Создание и поддержка сайтов для клиентов. Поддержка крупного легаси проекта на react.\nНесколько проектов с нуля в которых я занимался разработкой на react, разработкой на ванильном javascript, версткой по методологии БЭМ, работой с svg-графиками, анимацией,\nвнедрением семантической разметки schema.org, оптимизацией загрузки страниц.",
    "experience.placeofwork3.position": "Frontend developer",
    "experience.placeofwork3.company": "Feng Shui Crazy Journey",
    "experience.placeofwork3.dates": "07.2017 — 07.2019",
    "experience.placeofwork3.description": "Поддержка двух крупных сайтов на Wordpress. Верстка, внедрение системы контроля версий. Подключение и настройка различных веб-сервисов (генераторы форм, таймера, чаты, комментарии, рассылка писем...).",
    "contact.text.title": "Связаться",
    "contact.text.p1": "Рассматриваю как предложения о постоянной работе, так и конкретные проекты. По форме ниже вы можете связаться со мной, ваше сообщение придёт ко мне в телеграм.",
    "contact.form.button": "Отправить",
    "contact.form.alert.success": "Успешно отправлено",
    "contact.form.alert.error": "Ошибка отправки",
    "contact.form.name": "Имя",
    "contact.form.email": "Email",
    "contact.form.message": "Сообщение",
    "works.text.title": "Примеры кода",
    "skills.text.titlestack": "Стек технологий",
    "works.list.button": "Посмотреть",
    "works.list.item1.title": "Skillsetter",
    "works.list.item1.undertitle": "Перенос старого функционала с twig на react. Разработка и поддержка нового функционала. Разработка на react (context, react-router, ...), верстка (БЕМ, styled-components, написание сопутствующих скриптов на js)",
    "works.list.item2.title": "Метеозахист",
    "works.list.item2.undertitle": "Поддержка и разработка большого legacy-проекта на React.",
    "works.list.item3.title": "Рентфлот",
    "works.list.item3.undertitle": "Создание и поддержка клиентской части.",
    "works.list.item4.title": "Доска объявлений",
    "works.list.item4.undertitle": "Пример сайта объявлений. Можно создавать и редактировать свои объявления, просматривать и фильтровать чужие. В качестве бэка используется firebase.",
    "works.list.item5.title": "Сайт компании",
    "works.list.item5.undertitle": "Пример простенького сайта компании на реакте с использованием классовых компонентов.",
    "works.list.item6.title": "Rockit Club",
    "works.list.item6.undertitle": "Пример верстки сайта с различными анимациями и визуальными эффектами",
    "skills.text.title": "Навыки",
    "skills.text.p1": "Основной вектор моего развития - React и его экосистема.\n                        Также пишу и на чистом javascript.\n                        Хорошо верстаю, использую методологию БЭМ.\n                        Был опыт работы с Next.js и firebase.",
    "skills.text.p2": "Нахожусь в процессе изучения английского языка и typescript."
}