export default {
    "home.text.title.part1": "Привіт!",
    "home.text.title.part2": "Я Станіслав",
    "home.text.title.part3": "Frontend developer",
    "home.text.button.resume": "Резюме",
    "home.text.button.contact": "Зв'язатись зі мною",
    "sidebar.name": "Станіслав",
    "sidebar.menu.link1": "Досвід",
    "sidebar.menu.link2": "Навички",
    "sidebar.menu.link3": "Код",
    "sidebar.menu.link4": "Зв'язатись",
    "experience.text.title": "Досвід",
    "experience.text.p1": "На даний момент являюсь розробником на ReactJS з майже 3-річним досвідом з даною технологією і більш ніж 5-річним стажем роботи в ІТ сумарно.",
    "experience.text.p2": "Неповний перелік моїх обов'язків: розробка з нуля, підтримка легасі проектів, редизайн готового продукту без зміни функціоналу, оптимізація завантаження сторінки, покращення позиціонування сайтів у пошукових системах, впровадження shecma.org розмітки, робота з графікою (svg, анімації, різні медіа) , Впровадження системи git, інтеграція різних сторонніх сервісів, робота з SMS...",
    "experience.placeofwork1.position": "Frontend developer",
    "experience.placeofwork1.company": "Skillsetter",
    "experience.placeofwork1.dates": "07.2021 — 01.2023",
    "experience.placeofwork1.description": "Розробка освітньої платформи, що включає лендинги, навчальні курси, завдання з обробкою відповідей та інше.\nПеренесення існуючого функціоналу з twig на react, розробка нового функціоналу на react, верстка як html/sass так і за допомогою styled-components, редизайн.\nЯк стейт-менеджер використовувався React Context. Невелика кількість ванільного JS.",
    "experience.placeofwork2.position": "Frontend developer",
    "experience.placeofwork2.company": "Easy Agency",
    "experience.placeofwork2.dates": "09.2019 — 04.2021",
    "experience.placeofwork2.description": "Створення та підтримка сайтів для клієнтів. Підтримка великого легасі проекту на react.\nДекілька проектів з нуля в яких я займався розробкою на react, розробкою на ванільному javascript, версткою за методологією БЕМ, роботою з svg-графіками, анімацією,\nвикористанням семантичної розмітки schema.org, оптимізацією завантаження сторінок.",
    "experience.placeofwork3.position": "Frontend developer",
    "experience.placeofwork3.company": "Feng Shui Crazy Journey",
    "experience.placeofwork3.dates": "07.2017 — 07.2019",
    "experience.placeofwork3.description": "Підтримка двох великих веб-сайтів на Wordpress. Верстка, використання системи контролю версій. Підключення та налаштування різних веб-сервісів (генератори форм, таймера, чати, коментарі, розсилання листів...).",
    "contact.text.title": "Зв'язатись",
    "contact.text.p1": "Розглядаю як пропозиції щодо постійної роботи, так і конкретні проекти. За формою нижче, ви можете зв'язатися зі мною, ваше повідомлення прийде до мене в телеграм.",
    "contact.form.button": "Відправити",
    "contact.form.alert.success": "Успішно відправлено",
    "contact.form.alert.error": "Помилка відправлення",
    "contact.form.name": "Ім'я",
    "contact.form.email": "Email",
    "contact.form.message": "Повідомлення",
    "works.text.title": "Приклади коду",
    "skills.text.titlestack": "Стек технологій",
    "works.list.button": "Поглянути",
    "works.list.item1.title": "Skillsetter",
    "works.list.item1.undertitle": "Перенесення старого функціоналу з twig на react. Розробка та підтримка нового функціоналу. Розробка на react (context, react-router, ...), верстка (БЄМ, styled-components, написання супутніх скриптів на js)",
    "works.list.item2.title": "Метеозахист",
    "works.list.item2.undertitle": "Підтримка та розробка великого legacy-проєкту на React.",
    "works.list.item3.title": "Рентфлот",
    "works.list.item3.undertitle": "Створення та підтримка кліентської частини.",
    "works.list.item4.title": "Дошка оголошень",
    "works.list.item4.undertitle": "Приклад сайту оголошень. Можна створювати та редагувати свої оголошення, переглядати та фільтрувати чужі. Як бек використовується firebase.",
    "works.list.item5.title": "Сайт компанії",
    "works.list.item5.undertitle": "Приклад простенького сайту компанії на реакті з використанням класових компонентів.",
    "works.list.item6.title": "Rockit Club",
    "works.list.item6.undertitle": "Приклад верстки сайту з різними анімаціями та візуальними ефектами",
    "skills.text.title": "Навички",
    "skills.text.p1": "Основний вектор мого розвитку - React та його екосистема.\n                         Також пишу і на чистому JavaScript.\n                         Добре верстаю, використовую методологію БЕМ.\n                         Був досвід роботи з Next.js та firebase.",
    "skills.text.p2": "Знаходжуся в процесі вивчення англійської мови та typescript."
}