export default {
    "home.text.title.part1": "Hi!",
    "home.text.title.part2": "I'm Stanislav,",
    "home.text.title.part3": "Frontend developer",
    "home.text.button.resume": "Resume",
    "home.text.button.contact": "Contact me",
    "sidebar.name": "Stanislav",
    "sidebar.menu.link1": "Experience",
    "sidebar.menu.link2": "Skills",
    "sidebar.menu.link3": "Works",
    "sidebar.menu.link4": "Contact",
    "experience.text.title": "Experience",
    "experience.text.p1": "At the moment, I am a developer on ReactJS with almost 3 years of experience with this technology and also more than 5 years of work in IT in total.",
    "experience.text.p2": "An incomplete list of my responsibilities: development from scratch, support of legacy projects, redesign of the complete product without changing functionality, page loading optimization, improvement of site positioning in search engines, implementation of schema.org markup, work with graphics (svg, animation, various media), implementation of the git system, third-party services integration, work with SMS.",
    "experience.placeofwork1.position": "Frontend developer",
    "experience.placeofwork1.company": "Skillsetter",
    "experience.placeofwork1.dates": "07.2021 — 01.2023",
    "experience.placeofwork1.description": "Development of an educational platform, which includes landing pages, training courses, tasks with answer processing, etc.\nTransferring of existing functionality from twig to react, development of the new functionality to react, a layout both of html/asaa and using style components, redesign.\nAs the state manager was used React Context. A small amount of vanilla JS.",
    "experience.placeofwork2.position": "Frontend developer",
    "experience.placeofwork2.company": "Easy Agency",
    "experience.placeofwork2.dates": "09.2019 — 04.2021",
    "experience.placeofwork2.description": "Creation and support of sites for clients. Support of a large legacy project on React.\nSeveral projects from scratch in which I was involved in development on react, development on vanilla JS, layout according to BEM methodology with svg graphics, animation, using schema.org semantic markup, and page loading optimization.",
    "experience.placeofwork3.position": "Frontend developer",
    "experience.placeofwork3.company": "Feng Shui Crazy Journey",
    "experience.placeofwork3.dates": "07.2017 — 07.2019",
    "experience.placeofwork3.description": "Maintenance of two large websites on WordPress. Layout, usage of the version control system. Connecting and configuring various web services (form generators, timer, chats, comments, letter sending, etc.).",
    "contact.text.title": "Contact me",
    "contact.text.p1": "I consider both proposals for permanent employment and specific projects. You can contact me using the form below, your message will be delivered to me on Telegram.",
    "contact.form.button": "Send message",
    "contact.form.alert.success": "Success",
    "contact.form.alert.error": "Error",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.message": "Message",
    "works.text.title": "Code examples",
    "skills.text.titlestack": "Technology Stack",
    "works.list.button": "Go",
    "works.list.item1.title": "Skillsetter",
    "works.list.item1.undertitle": "Transferring the old functionality from Twig to React. Development and maintenance of the new functionality. Development on React (context, react-router, etc.), layout (BEM, styled components, writing concomitant scripts on JS).",
    "works.list.item2.title": "Meteozakhhist",
    "works.list.item2.undertitle": "Maintenance and development of the large legacy project.",
    "works.list.item3.title": "Rentflot",
    "works.list.item3.undertitle": "Creation and support of the client part.",
    "works.list.item4.title": "Notice board",
    "works.list.item4.undertitle": "An example of a classified site. Ability to create and edit your advertisements and view and filter others' ads. Firebase is used as a backend.",
    "works.list.item5.title": "Company website",
    "works.list.item5.undertitle": "An example of a simple company site on React using class components.",
    "works.list.item6.title": "Rockit Club",
    "works.list.item6.undertitle": "An example of a site layout with various animations and visual effects",
    "skills.text.title": "Skills",
    "skills.text.p1": " The main vector of my development is React and its ecosystem.\n                          I also write in pure JavaScript.\n                          Have a success in layout and BEM methodology usage. \n                          Had an experience working with Next.js and Firebase.",
    "skills.text.p2": "I'm in the process of learning English and typescript."
}